### ISSUE TITLE
code released

### ISSUE THREAD

**Issue by nhw649** [kaist-cvml-lab/part-clipseg#1]
I am very interested in the this project and wondering if you could share when you plan to make the source code available?

**Comment by JihoChoi** [comment]
Thank you for your interest in this project.
We apologize for the delay, but our team's paper is currently under review, which has delayed the code release.
However, we still plan to release the code by July.
We appreciate your patience and understanding.

Thank you.

**Comment by JihoChoi** [comment]
Thank you for your continued interest in this project.

We sincerely apologize for the additional delay.
We plan to release the code by mid-August.

We appreciate your patience and understanding during this time.

Thank you.

**Comment by codewithkeshavkr** [comment]
is there any Google Colab code version released?
